### ISSUE TITLE
Implement error handing for Rest class

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#493]
The testing infrastructure needs better error handling.

Error:
```
  Background:                                      # features/stop_move_type.feature:4
    Given Clean OpenHAB with latest Ruby Libraries # features/step_definitions/openhab.rb:6
      no implicit conversion of String into Integer (TypeError)
      ./features/support/openhab.rb:169:in `block in delete_rules'
      ./features/support/openhab.rb:168:in `delete_rules'
      ./features/step_definitions/openhab.rb:7:in `nil'
      features/stop_move_type.feature:5:in `Clean OpenHAB with latest Ruby Libraries'
```

**Comment by jimtng** [comment]
I'm not sure what caused this error - it seems that the Rest.rules didn't return the expected json data. I'm wondering if it's because openhab isn't ready yet. It's just a guess, but I can add `start_openhab` in the `Given('Clean OpenHAB with latest Ruby Libraries')`. `start_openhab` will call the rake openhab:start which will wait until openhab is ready.

Do you have any objections to this @boc-tothefuture ?

It will change the cucumber behaviour in that it will start openhab if it's not already started, whereas previously it would just quit with a bunch of errors.

**Comment by boc-tothefuture** [comment]
I have also found that sometimes OpenHab just doesn't respond to a rest request.. not sure if it had to do with it being started.

I am not sure if OpenHab start will break any of our tests?  It will probably slow them all down however.

**Comment by jimtng** [comment]
I just came across another error while cucumber is waiting for the rule to be loaded. This all relates to #425 

Error: 
https://github.com/boc-tothefuture/openhab-jruby/runs/4824019929?check_suite_focus=true

```
    When I deploy the rules file                            # features/step_definitions/openhab_rules.rb:117
      Rule not added (RuntimeError)
      ./features/support/support.rb:10:in `wait_until'
      ./features/step_definitions/openhab_rules.rb:61:in `wait_for_rule'
      ./features/step_definitions/openhab_rules.rb:75:in `deploy_ruby_file'
      ./features/step_definitions/openhab_rules.rb:50:in `deploy_rule'
      ./features/step_definitions/openhab_rules.rb:118:in `nil'
      features/comparisons.feature:585:in `I deploy the rules file'
```

**Comment by boc-tothefuture** [comment]
An alternative, and I thought I implemented this was to retry those failed requests.

**Comment by jimtng** [comment]
I'm still not fully familiar with the whole testing / build infrastructure, but I saw that warmup.rb is executed/tested before cucumber starts, so it seems that openhab should be ready by the time cucumber starts, so yeah perhaps adding `start_openhab` won't make a difference.

> An alternative, and I thought I implemented this was to retry those failed requests.

That should help.

**Comment by jimtng** [comment]
Or do we need to increase the timeout settings?

**Comment by boc-tothefuture** [comment]
I think the timeout is 60 seconds.  It appeared to me that we sometime just get blank and 404.responses from OH..  I haven't found a root cause yet.

**Comment by jimtng** [comment]
It seems that #499 didn't fix this issue. It's still happening with the same error message

https://github.com/boc-tothefuture/openhab-jruby/runs/4877952728?check_suite_focus=true

```
no implicit conversion of String into Integer (TypeError)
      ./features/support/openhab.rb:169:in `block in delete_rules'
      ./features/support/openhab.rb:168:in `delete_rules'
      ./features/step_definitions/openhab.rb:7:in `nil'
```

**Comment by jimtng** [comment]
And happened again here https://github.com/boc-tothefuture/openhab-jruby/runs/4881769739?check_suite_focus=true

Perhaps it hasn't finished doing warmup? We could try just setting the retry count to something high like 15-20. The intermittent aspect makes it hard to reproduce

**Comment by jimtng** [comment]
Oops the error is still happening
https://github.com/boc-tothefuture/openhab-jruby/runs/4891007168?check_suite_focus=true

**Comment by jimtng** [comment]
I have finally managed to reproduce the error and gathered a useful clue:
```
{"error":{"message":"Invalid credentials","http-code":401}}
```

**Comment by boc-tothefuture** [comment]
The causes of that could be:

1. For some reason we aren't sending credentials on this request
2. The setup code to set credentials didn't run (every test on every runner should fail - so seems unlikely)
3. We send credentials but there is a defect in OpenHab

Odds are it is 1 or 3.  Any other options we can think of?

**Comment by jimtng** [comment]
Not really sure of the causes at the moment. Do you know how to get httparty / persistent adapter to re-connect? I'm thinking we should redefine #get inside `Rest` and implement check for this 401 error, and do the reconnection there, with retry. I'm new to the 'httparty' and still feeling my way around ruby.

**Comment by jimtng** [comment]
I don't know how the persistent connection works in the library, and when the connection is being persisted and throughout what process. However, I suspect that (persistent connection's) timeout (and keepalive) has something to do with it. I'm curious how it performs keepalive when httparty isn't being called whilst the cucumber tests are running. In any case, the best solution is still to have some form of error handling.

**Comment by jimtng** [comment]
@boc-tothefuture how do I do some logging (without resorting to raising an exception) from within features/support/openhab.rb and where would the log go?

**Comment by boc-tothefuture** [comment]
You just do puts or pp and it will go to stdout, there is I also think a log method which should be available as part of cucumber which still just goes to stdout by default.

If you want to log to specific file you would need to 'include logger' from Ruby std library and configure where you want it to go.

**Comment by jimtng** [comment]
More info: In openhab.log:
```
2022-01-21 13:29:32.410 [WARN ] [ore.io.rest.auth.internal.AuthFilter] - Unauthorized API request: Basic authentication with username/password is not allowed
```

**Comment by jimtng** [comment]
I'm prepping a PR t
